var GAME_LEVELS = [
  ["                                                                                                                 ",
   "                                                                                                                 ",
   "  o o o o o o o o o o o o o o o o o     o                                                                        ",
   "                                                                                                                 ",
   "  xxx  xxx  xxx xxx  x     xx   xx     xxx                                                                       ",
   "  x  x  x  x       x x x  x  x x  x             o                                                                ",
   "  x  x  x  x xx  xx  xxxx  xx  x  x                                                                              ",
   "  x  x  x  x  x    x   x  x  x x  x            xxx                                                               ",
   "  xxx  xxx  xx  xxx    x   xx   xx          o                                                                    ",
   "                                                                                                                 ",
   "                                           xxx                                                                   ",
   "                                    o o                                                                          ",
   "                                                                o         o                                      ",
   "                                   xxxxx                                                                     xxxx",
   "xxxx                                       o o             o         o         o                           o  xff",
   "ffx                     o                                                                                  o  xff",
   "ffx                     o                 xxxxx           xxx       xxx       xxx               x   x      o  xxf",
   "ffx          xxxx       o                                                                   x o x o x o x  o   xf",
   "ffx  @       xffx       s                                                                   x   x   x   x      xf",
   "ffxxxxxxxxxxxxffxxxxxxxxxxxxxxx^^^xxxxxxxxxxxxxxxxxxxx^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^xxxxxxxxxxxxxxxxxxxxxxxxxxf",
   "ffffffffffffffffffffffffffffffx!!!xffffffffffffffffffx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xffffffffffffffffffffffffff",
   "ffffffffffffffffffffffffffffffx!!!xffffffffffffffffffx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xffffffffffffffffffffffffff",
   "ffffffffffffffffffffffffffffffx!!!xffffffffffffffffffx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xffffffffffffffffffffffffff",
   "ffffffffffffffffffffffffffffffx!!!tttttttttttttttttttt!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xffffffffffffffffffffffffff",
   "ffffffffffffffffffffffffffffffx!!!xffffffffffffffffffx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xffffffffffffffffffffffffff",
   "ffffffffffffffffffffffffffffffxxxxxffffffffffffffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxffffffffffffffffffffffffff"],
  ["                                                                                                                                     ",
   "                      o                            o                 o        o                o      o      o      o                ",
   "                                                                                                                                     ",
   "                     xxx                          xxx               xxx      xxx              xxx    xxx    xxx    xxx               ",
   "                       o                          o     o       o                  o     o      o                                    ",
   "                                                                                                                                     ",
   "                      xxx                        xxx    o      xxx                xxx    o     xxx                                   ",
   "                      o                            o            o                              o                                     ",
   "                                                        o                                o              o      o                     ",
   "                     xxx                          xxx        xxx                              xxx                                    ",
   "                       o                         o      o      o                         o      o      xxx    xxx                    ",
   "                                                                                                                                     ",
   "                      xxx                       xxx     o     xxx                        o     xxx                                   ",
   "                          o                   o                 o                   o          o                                     ",
   "                                                        o                                o                                           ",
   "                         xxx                 xxx               xxx                xxx         xxx                                    ",
   "                                o       o               o           o         o          o       o                                   ",
   "                                                                                                                                     ",
   "                               xxx     xxx              x          xxx       xxx         x      xxx                                  ",
   "                                                                                                                                     ",
   "   @                                                                                                                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^xxxxxxxxxxxxxxxxxxxxxx",
   "ffffffffffffffffffffffffffff!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ffffffffffffffffffffff",
   "ffffffffffffffffffffffffffff!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ffffffffffffffffffffff",],
  [" @                                                                                                                                                                                            ",
   "                                                                                                                                                                                              ",
   "                                                                                                                                                                                              ",
   "                                                                                                                                                                                              ",
   "                                                                                                                            o      o                                                          ",
   "                                                                                                                     o                                                                        ",
   "                                                                                                               o            x      x      o                                                   ",
   "                                                                                                                     x                                                                        ",
   "                                                                                                         o     x                          x      o                                            ",
   "                                                         o      o                                 o                   o        o                                                              ",
   "                                                                       o                                 x                                       x                                            ",
   "                                                   o     x      x                          o      x         o     o        o          o              o                                        ",
   "                                                                       x      o                                                                                                               ",
   "               o                                   x                                 o     x                    o                    o               x                                        ",
   "                      o                        o            o                 x                       o                                        o      o                                       ",
   "          o    x             o                         o                   o         x                                       o             o                                                  ",
   "                      x             o     o    x                     o                       o                        o                               x                                       ",
   "          x                  x                             o                                       o                             o                  o                                         ",
   "       o                            x     x          o            o                  o                                   o              o                                                     ",
   "              o                                            x                    o                      o                                            x                                         ",
   "       x                       o                o    x            x    o                    o                 o                     o            o                                            ",
   "      o             o                  o                                                         o     x                       o                                                              ",
   "               o         o                      x                      x      o                               x    o                             x                                            ",
   "      x                          o          o                                        o      o    x                                           o                                                ",
   "          o                                                                   x                                    x     o                                                  oooo ooo oo   o   ",
   "                 o                     o    x                                        x      x                                   o      o     x                              o     o  o o  o   ",
   "          x              o      o                                                                                        x                                                  ooo   o  o  o o   ",
   "                 x                     x                                                                                        x      x                                    o    ooo o   oo   ",
   "                         x      x                                                                                                                                         xxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                                                                                              ",
   "                                                                                                                                                                                              ",
   "                                                                                                                                                                                              ",
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exporto)
  module.exporto = GAME_LEVELo;
